services:
  api:
    image: ghcr.io/rpitv/glimpse-api:latest
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - apps/api/.env.docker
    networks:
      - glimpse_network
    profiles:
      - production
    depends_on:
      - db
      - redis
      - rabbitmq

  ui:
    image: ghcr.io/rpitv/glimpse-ui:latest
    restart: unless-stopped
    ports:
      - "5173:80"
    networks:
      - glimpse_network
    profiles:
      - production
    depends_on:
      - api

  video:
    image: ghcr.io/rpitv/glimpse-video:latest
    restart: unless-stopped
    ports:
      - "1936:1935"
    networks:
      - glimpse_network
    profiles:
      - production

  video-control:
    image: ghcr.io/rpitv/glimpse-video-control:latest
    restart: unless-stopped
    networks:
      - glimpse_network
    env_file:
      - apps/video-control/.env
    profiles:
      - production

  db:
    image: postgres:14
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - .db-data:/var/lib/postgresql/data
    env_file:
      - apps/api/.env.docker
    networks:
      - glimpse_network

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - .redis-data:/data
    networks:
      - glimpse_network

  rabbitmq:
    image: rabbitmq:4.0-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - glimpse_network

networks:
  glimpse_network:
    name: glimpse_network
