#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# ! WARNING DOCKER IS CURRENTLY NOT SUPPORTED !
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
# Score Sync from Daktronics will not work
# inside Docker.
#
# If you wish to continue go to "package.json"
# and inside the "scripts" change:
#		"watch:browser": "vite",
# to:
#		"watch:browser": "vite --host=0.0.0.0",
# then you can run this inside Docker.
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# ! WARNING DOCKER IS CURRENTLY NOT SUPPORTED !
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
version: "3.9"
services:
  graphics:
    build: .
    ports:
      - "9090:80"
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=trace
      - DUMP_RTD=false
    volumes:
      - ./.nodecg/cfg:/usr/src/app/cfg
      - ./.nodecg/db:/usr/src/app/db
      - ./.nodecg/assets:/usr/src/app/assets
      - ./dumps:/usr/src/app/dumps
      - .:/usr/src/app/bundles/glimpse-graphics
      - /usr/src/app/bundles/glimpse-graphics/node_modules
    command: npm --prefix "./bundles/glimpse-graphics" run dev
    networks:
      - glimpse_network
networks:
  glimpse_network:
    name: glimpse_network
